name: Check Root Files And Auto-Merge

on:
  pull_request:
    paths:
      - '**/*'  # Run this on any changes made to the repository

jobs:
  check_deletions_and_root_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request if No Issues
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request: ${{ github.event.pull_request.number }}
