name: Prevent File Deletions and Check Root Files

on:
  pull_request:
    paths:
      - '**/*'  # Run this on any changes made to the repository

jobs:
  check_deletions_and_root_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for file deletions
        id: check_deletions
        run: |
          # Find deleted files in the pull request
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep -e 'D' > deleted_files.txt
          
          if [ -s deleted_files.txt ]; then
            echo "Error: The following files were deleted in this pull request:"
            cat deleted_files.txt
            echo "has_deleted_files=true" >> $GITHUB_ENV
          else
            echo "No files deleted. Proceeding with the pull request."
            echo "has_deleted_files=false" >> $GITHUB_ENV
          fi

      - name: Check for unexpected files in the root directory
        id: check_root_files
        run: |
          # List files at the root of the repository
          root_files=$(ls -1 | grep -v 'README.md' | grep -v '/')
          
          # If any non-directory files are found at the root, fail the check
          if [ -n "$root_files" ]; then
            echo "Error: The following unexpected files were found in the root directory:"
            echo "$root_files"
            echo "has_unexpected_root_files=true" >> $GITHUB_ENV
          else
            echo "Root directory only contains folders or README.md."
            echo "has_unexpected_root_files=false" >> $GITHUB_ENV

      - name: Merge Pull Request if No Issues
        if: env.has_deleted_files == 'false' && env.has_unexpected_root_files == 'false'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request: ${{ github.event.pull_request.number }}
